version: '1.0'
services:
  sensor-appliction:
    image: ${IMAGE_NAME}
    container_name: sensor
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MONGODB_URL=${MONGODB_URL}
      - BUCKET_NAME=${BUCKET_NAME}